package com.springboot.dto;

import com.alibaba.fastjson.annotation.JSONField;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * @author 吴金才
 * @Description *
 * @date 2021/9/7 9:33 上午
 */
@Data
@NoArgsConstructor
public class SapConfig {
    /*** 域名 */
    @JSONField(name = "baseUrl")
    private String baseUrl;
    /*** 用户名 */
    @JSONField(name = "username")
    private String username;
    /*** 密码 */
    @JSONField(name = "password")
    private String password;
    /*** 标准订单类型 */
    @JSONField(name = "StandardSalesOrder")
    private String standardSalesOrder;
    /*** 销售组织 */
    @JSONField(name = "SalesOrganization")
    private String salesOrganization;
    /*** 分销渠道 */
    @JSONField(name = "DistributionChannel")
    private String distributionChannel;
    /*** 产品组 */
    @JSONField(name = "OrganizationDivision")
    private String organizationDivision;
    /*** 销售办事处 */
    @JSONField(name = "SalesOffice")
    private String salesOffice;
    /*** 销售组 */
    @JSONField(name = "SalesGroup")
    private String salesGroup;
    /*** 默认客户代码 */
    @JSONField(name = "Customer")
    private String customer;
    /*** 默认币种 */
    @JSONField(name = "Currency")
    private String currency;
    /*** 默认审批状态 */
    @JSONField(name = "SalesOrderAudtiStatus")
    private String salesOrderAudtiStatus;
    /*** 默认订单来源 */
    @JSONField(name = "OrderSource")
    private String orderSource;
    /*** 代发 */
    @JSONField(name = "IsReplace")
    private String isReplace;
    /*** 非代发 */
    @JSONField(name = "NotReplace")
    private String notReplace;
    /*** 默认项目类型 */
    @JSONField(name = "ItemCategory")
    private String itemCategory;
    /*** 默认代发仓库 */
    @JSONField(name = "ProductPlantReplace")
    private String productPlantReplace;
    /*** 默认非代发仓库 */
    @JSONField(name = "ProductPlantNotReplace")
    private String productPlantNotReplace;
    /*** 退款单类型 */
    @JSONField(name = "customerReturnType")
    private String customerReturnType;
    /*** 订单原因 */
    @JSONField(name = "sDDocumentReason")
    private String sDDocumentReason;
    /*** 退款单销售订单行项目号 */
    @JSONField(name = "customerReturnItemCategory")
    private String customerReturnItemCategory;
    /*** 默认检验代码 */
    @JSONField(name = "retMatlInspResultCode")
    private String retMatlInspResultCode;
    /*** 默认后续活动 */
    @JSONField(name = "CustRetItmFollowUpActivity")
    private String custRetItmFollowUpActivity;
    /*** 已接收物料 */
    @JSONField(name = "returnsMaterialHasBeenReceived")
    private String returnsMaterialHasBeenReceived;
    /*** 退款控制 */
    @JSONField(name = "returnsRefundProcgMode")
    private String returnsRefundProcgMode;
    /*** 退款单代发 */
    @JSONField(name = "yy1FdSfdfSdi")
    private String yy1FdSfdfSdi;
    /*** 采购订单类型 */
    @JSONField(name = "purchaseOrderType")
    private String purchaseOrderType;
    /*** 默认公司代码 */
    @JSONField(name = "companyCode")
    private String companyCode;
    /*** 默认创建人 */
    @JSONField(name = "createdByUser")
    private String createdByUser;
    /*** 默认采购组 */
    @JSONField(name = "purchasingGroup")
    private String purchasingGroup;
    /*** 默认采购组织 */
    @JSONField(name = "purchasingOrganization")
    private String purchasingOrganization;
    /*** 默认供应商 */
    @JSONField(name = "supplier")
    private String supplier;
    /*** 默认发票收据标识 */
    @JSONField(name = "invoiceIsExpected")
    private Boolean invoiceIsExpected;
    /*** 默认标识，基于收货的发票验证 */
    @JSONField(name = "invoiceIsGoodsReceiptBased")
    private Boolean invoiceIsGoodsReceiptBased;
    /*** 默认工厂 */
    @JSONField(name = "plant")
    private String plant;
    /*** 采购申请的项目编号 */
    @JSONField(name = "purchaseOrderItem")
    private String purchaseOrderItem;
    /*** 默认条件类型 */
    @JSONField(name = "ConditionType")
    private String conditionType;
    /*** 默认折让金额条件类型 */
    @JSONField(name = "discountConditionType")
    private String discountConditionType;
    /*** 货物移动引用类型 */
    @JSONField(name = "GoodsMovementRefDocType")
    private String goodsMovementRefDocType;
    /*** 货物移动类型 */
    @JSONField(name = "GoodsMovementType")
    private String goodsMovementType;
    /*** 货物移动代码 */
    @JSONField(name = "goodsMovementCode")
    private String goodsMovementCode;
    /*** 是否预约单 */
    @JSONField(name = "isPreOrder")
    private String isPreOrder;
    /*** 有赞侧虚拟仓库编码 */
    @JSONField(name = "virtualWarehouseCode")
    private String virtualWarehouseCode;
    /*** 有赞侧供应商编码 */
    @JSONField(name = "supplierCode")
    private String supplierCode;
    /*** 非代发供货仓库 */
    @JSONField(name = "NotReplaceStorageLocation")
    private String notReplaceStorageLocation;
    /*** 代发供货仓库 */
    @JSONField(name = "ReplaceStorageLocation")
    private String replaceStorageLocation;
    /*** ESB加密组织编码 */
    @JSONField(name = "OrganizationCode")
    private String organizationCode;
    /*** ESB加密系统编码 */
    @JSONField(name = "SystemCode")
    private String systemCode;
    /*** ESB加密 appCode */
    @JSONField(name = "AppCode")
    private String appCode;
    /*** 默认供货仓库 */
    @JSONField(name = "supplyingPlant")
    private String supplyingPlant;
    /*** ESB加密 token */
    @JSONField(name = "AppAccessToken")
    private String appAccessToken;
    /*** 有赞侧默认采购价 已无用  */
    @JSONField(name = "defaultPurchasePrice")
    private String defaultPurchasePrice;
    /*** 自定义订单类型  */
    @JSONField(name = "extOrderType")
    private String extOrderType;
}
